### ISSUE TITLE
Any plans for relay integration?

### ISSUE THREAD

**Issue by cdroulers** [mkmarek/graphql-dotnetcore#37]
Such as `node` field and `connection` fields?

**Comment by JarnoNijboer** [comment]
In my opinion @mkmarek shouldn't integrate Relay specific stuff into this project, since there are more GraphQL clients than Relay. It also deviates this project from the graphql-js reference implementation. I'd rather see an companion project target on Relay that implemented the all specific requirements for it. Facebook is also working actively on Relay 2 where they possibly could introduce breaking changes for the server-side requirements, and a project that implements the Relay specific implementation should support both Relay 1 and 2.

The `node` field is something you can do yourselves, like I have done. Just add a field named `node` to your root query and add a custom resolver where you deconstruct the global id e.g. `ClrType.FullName:IdOfInt32`. This allows you to figure out what type Relay ask for and what the actual id of the item is. Based on that info you should be able to resolve item and return the correct object.

One tip I have for you: I have implemented the resolvers for the complex types in separate classes, and I have a mapping for my GraphQLTypes and corresponding resolvers. In the resolve method of the `node` field, I extract the CLR type out of the given global id and then I use the mapping to find the resolver I need to invoke.

**Comment by cdroulers** [comment]
Sounds absolutely right! Thanks for the good post!

If I end up using dotnetcore, it'll probably be using [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) since it seems more active and already has Relay support.

The syntax is very verbose compared to this, but it has a lot more features so far. Thanks for your response!
